In [68]:
import pandas as pd
from os import error
import numpy as np

In [69]:
df_ptx = pd.read_csv(r'ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/ptbxl_database.csv')
df_scp = pd.read_csv(r'ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/scp_statements.csv')

In [70]:
# df_ptx.isna().sum()
clean_ptx = df_ptx.drop([
    'infarction_stadium1',
    'infarction_stadium2',
    'nurse',
    'site',
    'device',
    'report',
    'recording_date',
    'validated_by',
    'second_opinion',
    'initial_autogenerated_report',
    'validated_by_human',
    'static_noise'
    ], axis =1)

clean_ptx.isna().sum()

ecg_id                     0
patient_id                 0
age                       89
sex                        0
height                 14854
weight                 12408
scp_codes                  0
heart_axis              8505
baseline_drift         20230
burst_noise            21224
electrodes_problems    21807
extra_beats            19883
pacemaker              21544
strat_fold                 0
filename_lr                0
filename_hr                0
dtype: int64

In [71]:

clean_ptx = clean_ptx[clean_ptx['electrodes_problems'].isnull()]
# clean_ptx['electrodes_problems'].isnull()
# clean_ptx.isna().sum()

clean_ptx = clean_ptx[clean_ptx['pacemaker'].isnull()]

clean_ptx = clean_ptx.drop([
    'electrodes_problems',
    'pacemaker'
    ],axis=1 )

clean_ptx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ecg_id          21516 non-null  int64
 1   patient_id      21516 non-null  float64
 2   age             21431 non-null  float64
 3   sex             21516 non-null  int64
 4   height          6933 non-null   float64
 5   weight          9379 non-null   float64
 6   scp_codes       21516 non-null  object
 7   heart_axis      13315 non-null  object
 8   baseline_drift  1584 non-null   object
 9   burst_noise     594 non-null    object
 10  extra_beats     1902 non-null   object
 11  strat_fold      21516 non-null  int64
 12  filename_lr     21516 non-null  object
 13  filename_hr     21516 non-null  object
dtypes: float64(4), int64(3), object(7)
memory usage: 2.5+ MB

In [72]:
from sklearn.impute import KNNImputer

dummy_var = clean_ptx[['height','weight','age']]
dummy = pd.get_dummies(dummy_var, drop_first=True)
dummy_var.info()
dummy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  6933 non-null   float64
 1   weight  9379 non-null   float64
 2   age     21431 non-null  float64
dtypes: float64(3)
memory usage: 672.4 KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  6933 non-null   float64
 1   weight  9379 non-null   float64
 2   age     21431 non-null  float64
dtypes: float64(3)
memory usage: 672.4 KB

In [73]:
clean_ptx = clean_ptx.drop(['height','weight','age'], axis = 1)
clean_ptx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ecg_id          21516 non-null  int64
 1   patient_id      21516 non-null  float64
 2   sex             21516 non-null  int64
 3   scp_codes       21516 non-null  object
 4   heart_axis      13315 non-null  object
 5   baseline_drift  1584 non-null   object
 6   burst_noise     594 non-null    object
 7   extra_beats     1902 non-null   object
 8   strat_fold      21516 non-null  int64
 9   filename_lr     21516 non-null  object
 10  filename_hr     21516 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 2.0+ MB

In [74]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import KNNImputer
print(dummy.info())
scaler = MinMaxScaler()
dummy = pd.DataFrame(scaler.fit_transform(dummy), columns = dummy.columns, index = dummy.index)
print(dummy.info())
imputer = KNNImputer(n_neighbors=5)
dummy = pd.DataFrame(imputer.fit_transform(dummy),columns = dummy.columns, index = dummy.index)
print(dummy.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  6933 non-null   float64
 1   weight  9379 non-null   float64
 2   age     21431 non-null  float64
dtypes: float64(3)
memory usage: 672.4 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  6933 non-null   float64
 1   weight  9379 non-null   float64
 2   age     21431 non-null  float64
dtypes: float64(3)
memory usage: 672.4 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  21516 non-null  float64
 1   weight  21516 non-null  float64
 2   age     21516 non-null  float64
dtypes: float64(3)
memory usage: 672.4 KB
None

In [75]:
dummy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  21516 non-null  float64
 1   weight  21516 non-null  float64
 2   age     21516 non-null  float64
dtypes: float64(3)
memory usage: 672.4 KB

In [76]:
dummy_trans = scaler.inverse_transform(dummy)
dummy = pd.DataFrame({'height' : dummy_trans[:, 0], 'weight' : dummy_trans[:, 1], 'age' : dummy_trans[:, 2]}, columns = dummy.columns, index = dummy.index )
clean_ptx = pd.concat([clean_ptx, dummy], axis = 1)

In [77]:
clean_ptx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21516 entries, 0 to 21836
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ecg_id          21516 non-null  int64
 1   patient_id      21516 non-null  float64
 2   sex             21516 non-null  int64
 3   scp_codes       21516 non-null  object
 4   heart_axis      13315 non-null  object
 5   baseline_drift  1584 non-null   object
 6   burst_noise     594 non-null    object
 7   extra_beats     1902 non-null   object
 8   strat_fold      21516 non-null  int64
 9   filename_lr     21516 non-null  object
 10  filename_hr     21516 non-null  object
 11  height          21516 non-null  float64
 12  weight          21516 non-null  float64
 13  age             21516 non-null  float64
dtypes: float64(4), int64(3), object(7)
memory usage: 2.5+ MB

In [78]:
clean_ptx.isna().sum()

ecg_id                0
patient_id            0
sex                   0
scp_codes             0
heart_axis         8201
baseline_drift    19932
burst_noise       20922
extra_beats       19614
strat_fold            0
filename_lr           0
filename_hr           0
height                0
weight                0
age                   0
dtype: int64

In [79]:
ptb_dir = "ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.1/"

# Reads the scp csv file with the category as index
scp_df = pd.read_csv(ptb_dir+'scp_statements.csv', index_col=0)

subclasses = scp_df[scp_df["diagnostic"] == 1.0][["diagnostic_subclass", "diagnostic_class"]]
subclasses

        diagnostic_subclass diagnostic_class
NDT                    STTC             STTC
NST_                   NST_             STTC
DIG                    STTC             STTC
LNGQT                  STTC             STTC
NORM                   NORM             NORM
IMI                     IMI               MI
ASMI                    AMI               MI
LVH                     LVH              HYP
LAFB              LAFB/LPFB               CD
ISC_                   ISC_             STTC
IRBBB                 IRBBB               CD
1AVB                   _AVB               CD
IVCD                   IVCD               CD
ISCAL                  ISCA             STTC
CRBBB                 CRBBB               CD
CLBBB                 CLBBB               CD
ILMI                    IMI               MI
LAO/LAE             LAO/LAE              HYP
AMI                     AMI               MI
ALMI                    AMI               MI
ISCIN                  ISCI             STTC
INJAS                   AMI               MI
LMI                     LMI               MI
ISCIL                  ISCI             STTC
LPFB              LAFB/LPFB               CD
ISCAS                  ISCA             STTC
INJAL                   AMI               MI
ISCLA                  ISCA             STTC
RVH                     RVH              HYP
ANEUR                  STTC             STTC
RAO/RAE             RAO/RAE              HYP
EL                     STTC             STTC
WPW                     WPW               CD
ILBBB                 ILBBB               CD
IPLMI                   IMI               MI
ISCAN                  ISCA             STTC
IPMI                    IMI               MI
SEHYP                 SEHYP              HYP
INJIN                   IMI               MI
INJLA                   AMI               MI
PMI                     PMI               MI
3AVB                   _AVB               CD
INJIL                   IMI               MI
2AVB                   _AVB               CD

In [80]:
from ast import literal_eval

# Convert json string as python object
scp_codes = clean_ptx["scp_codes"].apply(lambda x : literal_eval(x))
def create_classification(scpc: dict):
  
  for x, _ in scpc.items():
    try:
      return subclasses.loc[x]["diagnostic_class"]
    except KeyError:
      pass
  
  return None
    
# For every scp_codes in df, we will create a new categorical thingy
clean_ptx["scp_result"] = scp_codes.apply(create_classification)
clean_ptx.head()

,ecg_id,patient_id,sex,scp_codes,heart_axis,baseline_drift,burst_noise,extra_beats,strat_fold,filename_lr,filename_hr,height,weight,age,scp_result
0,1,15709.0,1,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}",NaN,NaN,NaN,NaN,3,records100/00000/00001_lr,records500/00000/00001_hr,162.6,63.0,56.0,NORM
1,2,13243.0,0,"{'NORM': 80.0, 'SBRAD': 0.0}",NaN,NaN,NaN,NaN,2,records100/00000/00002_lr,records500/00000/00002_hr,176.2,70.0,19.0,NORM
2,3,20372.0,1,"{'NORM': 100.0, 'SR': 0.0}",NaN,NaN,NaN,NaN,5,records100/00000/00003_lr,records500/00000/00003_hr,167.6,69.0,37.0,NORM
3,4,17014.0,0,"{'NORM': 100.0, 'SR': 0.0}",NaN,", II,III,AVF",NaN,NaN,3,records100/00000/00004_lr,records500/00000/00004_hr,173.0,82.0,24.0,NORM
4,5,17448.0,1,"{'NORM': 100.0, 'SR': 0.0}",NaN,", III,AVR,AVF",NaN,NaN,4,records100/00000/00005_lr,records500/00000/00005_hr,176.2,70.0,19.0,NORM

In [81]:
clean_ptx.to_csv('ultra_cleanptbxl.csv')